name: Build .exe on Release

on:
  release:
    types: [published]  # Trigger the workflow when a new release is created
  workflow_dispatch:  # Allow manual trigger from the GitHub Actions tab

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Replace with your Python version

      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install the dependencies listed in requirements.txt

      - name: Install PyInstaller
        run: |
          pip install pyinstaller  # Ensure PyInstaller is installed

      - name: Build the .exe file
        run: |
          pyinstaller --onefile --distpath ./dist --workpath ./build your_script.py  # Replace with your script name

      - name: Upload the .exe file as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-executable
          path: ./dist/your_script.exe  # Path to the built .exe file
