name: Sync main to docs

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important: ensures full history is available
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git identity
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Fetch all branches
        run: git fetch origin

      - name: Checkout docs branch
        run: git checkout docs

      - name: Merge main into docs
        run: |
          git merge origin/main --no-ff --commit --allow-unrelated-histories -m "Sync main to docs"

      - name: Push changes
        run: git push origin docs
