name: Sync Main to Docs

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config user.name "Your Name"
          git config user.email "your-email@example.com"

      - name: Fetch docs branch
        run: git fetch origin docs

      - name: Merge main into docs
        run: |
          git checkout docs
          git merge origin/main --no-ff --commit -m "Sync main to docs"
        
      - name: Push changes to docs
        run: git push origin docs
